name: CI

on:
  push:
    branches: [ "main" ]
    paths:
    - 'appserviceplan.bicep'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  scan-bicep-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run Microsoft Security DevOps Analysis
      uses: microsoft/security-devops-action@v1.10.0
      id: msdo
      with:
        categories: 'IaC'
  
    - name: Upload results to security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
  
  preview:
    needs: scan-bicep-code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - uses: Azure/cli@v1
      name: Run what-if
      with:
        inlineScript: |
          az deployment group what-if --resource-group ${{ secrets.Azure_RG }} --template ./appserviceplan.bicep
  
  deploy-infra:
    needs: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./appserviceplan.bicep
          failOnStdErr: false
      
#      - name: bicep-build-output
#        uses: Azure/bicep-build-action@v1.0.1
#        with:
#          # Bicep main file path
#          bicepFilePath: appserviceplan.bicep
#          # ARM template output path
#          outputFilePath: ./azuredeploy.json
