name: CI

on:
  push:
    branches: [ "main" ]
    paths:
    - 'appserviceplan.bicep'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.1
        with:
          # Bicep main file path
          bicepFilePath: appserviceplan.bicep
          # ARM template output path
          outputFilePath: ./azuredeploy.json
