name: CI

on:
  push:
    branches: [ "main" ]
    paths:
    - 'appserviceplan.bicep'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.RG_D_TEST }}
          template: ./appserviceplan.bicep
          #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
          failOnStdErr: false
      
#      - name: bicep-build-output
#        uses: Azure/bicep-build-action@v1.0.1
#        with:
#          # Bicep main file path
#          bicepFilePath: appserviceplan.bicep
#          # ARM template output path
#          outputFilePath: ./azuredeploy.json
